Fixes missing `let` in `for...of` causing issues
```
ReferenceError: assignment to undeclared variable child
```

When using ES modules (I assume that's the root cause), the absence of `let` breaks this script.